### PR TITLE
Add mailto to list of allowed schemes

### PR DESCRIPTION
**Pull request by leotsarev**
It seems safe to allow also "mailto" scheme.
If no, please add way to configure it

### CODE REVIEW

**Comment by leotsarev** [comment]
Thanks! Please ping me when you will release update NuGet package...

**Comment by leotsarev** [comment]
Hi @cakkermans ! Could you please release NuGet package with this update?

**Comment by cakkermans** [comment]
Done: https://www.nuget.org/packages/Vereyon.Web.HtmlSanitizer/1.2.1

**Comment by leotsarev** [comment]
Great!

**Pull request merged**
