### PR TITLE
Allow optional sanitization of css classes

### PR DESCRIPTION
**Pull request by speshulk926**
I wanted the option to sanitize css classes because I am using this in a "sitewide" approach that pulls text from a database as well as a conditional approach which is more tailored. I need the ability to turn off sanitization of css classes because I don't want to add every single css class that is available to my site.

### CODE REVIEW

**Comment by speshulk926** [comment]
Do you think this is not a good idea to do or do you think there is a better implementation of it?

**Comment by cakkermans** [comment]
Sounds like a good plan to me. I merged the change. Will push a new release as soon as I wrote some tests for it.

**Comment by speshulk926** [comment]
Any chance we can get the nuget package updated soon?  =D

**Comment by cakkermans** [comment]
I just uploaded it: 
https://www.nuget.org/packages/Vereyon.Web.HtmlSanitizer/

Met vriendelijke groet,

Christ Akkermans, Bsc
W: http://www.vereyon.nl
E: c.akkermans@vereyon.nl

**Pull request merged**
