### PR TITLE
Allow safe attributes for list

### PR DESCRIPTION
**Pull request by leotsarev**
"start", "type" and "reversed" are perfectly fine attributes for OrderedList
So are "value" for list item.
Also, "start" and "type" attribute required for being able to correct rendering of markdown

### CODE REVIEW

**Comment by leotsarev** [comment]
Hi @cakkermans 
could you please set my expectations about whether you will look into this? It seems pretty easy/safe and in line with SimpleHtml5Sanitizer theme "allow things that are no-brain safe".

**Comment by cakkermans** [comment]
Sorry, I'm sort of busy. I merged the commit as it looks fine and the attributes are indeed valid.
Do you expect a new Nuget package?

**Comment by leotsarev** [comment]
>Do you expect a new Nuget package?

No, I'm not. It's simple workaround in my code (I have to enable other not-so-safe tags anyway), so I'm fine  with this released with "some next release in some future". I just want to contribute something back.

**Comment by cakkermans** [comment]
In that case you are very welcome. I'll include your changes in the next release.

**Pull request merged**
